import Header from "../../public/layout/header";
import Sidebar from "../../public/layout/sidebar";

/*---Nifty Css---*/
import "../../public/assets/css/bootstrap.css";
import "../../public/assets/css/nifty.css";
// import "../../public/assets/css/bootstrap.min.css";

/*---Bootstrap Css---*/
// import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <main>
      <script src="/assets/vendors/popper.min.js" defer></script>
      <script src="/assets/vendors/bootstrap.min.js" defer></script>
      <script src="/assets/js/nifty.js" defer></script>
      <script src="/assets/vendors/mdDateTimePicker.min.js" defer></script>
      <Header />
      <Sidebar />
      <body>{children}</body>
    </main>
  );
}
